"""The argument map (issue #572): positions and relations (this package)
and, in later PRs, the door, the landing, and the corridor. See
`axial.argmap.build` for the build pipeline and `specs/PHASE-B.md`'s
argument-map section for the artifact contract."""

from axial.argmap.build import (
    BAG_DISTANCE_THRESHOLD,
    EXTRACT_SLICE,
    MAX_NEIGHBOURHOOD,
    MERGE_DISTANCE_THRESHOLD,
    PASS_NAME,
    RELATE_PASS_NAME,
    TARGET_NEIGHBOURHOOD,
    WORKERS,
    CorruptReadsLedgerError,
    CorruptRelationsLedgerError,
    ExtractJob,
    MapError,
    Neighbourhood,
    Passage,
    assign_position_ids,
    author_spread,
    bag_passages,
    build_jobs,
    build_neighbourhoods,
    compute_corpus_pin,
    extract_positions_for_slice,
    merge_positions,
    relate_neighbourhood,
    render_claims_blind,
    render_positions_blind,
    run_extraction,
    run_map_build,
    run_relations,
    select_passages,
)

__all__ = [
    "BAG_DISTANCE_THRESHOLD",
    "EXTRACT_SLICE",
    "MAX_NEIGHBOURHOOD",
    "MERGE_DISTANCE_THRESHOLD",
    "PASS_NAME",
    "RELATE_PASS_NAME",
    "TARGET_NEIGHBOURHOOD",
    "WORKERS",
    "CorruptReadsLedgerError",
    "CorruptRelationsLedgerError",
    "ExtractJob",
    "MapError",
    "Neighbourhood",
    "Passage",
    "assign_position_ids",
    "author_spread",
    "bag_passages",
    "build_jobs",
    "build_neighbourhoods",
    "compute_corpus_pin",
    "extract_positions_for_slice",
    "merge_positions",
    "relate_neighbourhood",
    "render_claims_blind",
    "render_positions_blind",
    "run_extraction",
    "run_map_build",
    "run_relations",
    "select_passages",
]
